// @ts-nocheck — generated by `stellar contract bindings typescript`; not hand-maintained.
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import { Client as ContractClient, Spec as ContractSpec } from "@stellar/stellar-sdk/contract";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CBQBRQGVPSNINIL3P3GG2HRE6QPBY52A5CSCJ73ACSMW3IBWQ6OPS7VW",
  }
} as const

export const Errors = {
  1: {message:"ReputationNotSet"},
  2: {message:"NotInitialized"}
}

export type DataKey = {tag: "Admin", values: void} | {tag: "JobWasm", values: void} | {tag: "Reputation", values: void} | {tag: "Jobs", values: void} | {tag: "Registered", values: readonly [string]};


export interface Client {
  /**
   * Construct and simulate a is_job transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * The registry check the reputation contract relies on: true only for escrows this
   * factory deployed.
   */
  is_job: ({address}: {address: string}, options?: MethodOptions) => Promise<AssembledTransaction<boolean>>

  /**
   * Construct and simulate a get_admin transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_admin: (options?: MethodOptions) => Promise<AssembledTransaction<string>>

  /**
   * Construct and simulate a job_count transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  job_count: (options?: MethodOptions) => Promise<AssembledTransaction<u32>>

  /**
   * Construct and simulate a list_jobs transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  list_jobs: (options?: MethodOptions) => Promise<AssembledTransaction<Array<string>>>

  /**
   * Construct and simulate a create_job transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Deploys a fresh escrow for one engagement and records it, so that the reputation
   * contract can later confirm — via `is_job` — that the escrow is genuinely ours.
   */
  create_job: ({client, freelancer, arbiter, token, amounts, deadline}: {client: string, freelancer: string, arbiter: string, token: string, amounts: Array<i128>, deadline: u64}, options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a get_reputation transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_reputation: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a set_reputation transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Wires in the reputation contract. Separate from the constructor because the
   * reputation contract needs this factory's address to exist first, so the two are
   * deployed in sequence and linked afterwards.
   */
  set_reputation: ({reputation}: {reputation: string}, options?: MethodOptions) => Promise<AssembledTransaction<null>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
        /** Constructor/Initialization Args for the contract's `__constructor` method */
        {admin, job_wasm}: {admin: string, job_wasm: Buffer},
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy({admin, job_wasm}, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAAAgAAAAAAAAAQUmVwdXRhdGlvbk5vdFNldAAAAAEAAAAAAAAADk5vdEluaXRpYWxpemVkAAAAAAAC",
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAABQAAAAAAAAAAAAAABUFkbWluAAAAAAAAAAAAAAAAAAAHSm9iV2FzbQAAAAAAAAAAAAAAAApSZXB1dGF0aW9uAAAAAAAAAAAAAAAAAARKb2JzAAAAAQAAAAAAAAAKUmVnaXN0ZXJlZAAAAAAAAQAAABM=",
        "AAAABQAAAAAAAAAAAAAACkpvYkNyZWF0ZWQAAAAAAAEAAAALam9iX2NyZWF0ZWQAAAAABAAAAAAAAAAGY2xpZW50AAAAAAATAAAAAQAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAEAAAAAAAAAA2pvYgAAAAATAAAAAAAAAAAAAAAFaW5kZXgAAAAAAAAEAAAAAAAAAAI=",
        "AAAAAAAAAGJUaGUgcmVnaXN0cnkgY2hlY2sgdGhlIHJlcHV0YXRpb24gY29udHJhY3QgcmVsaWVzIG9uOiB0cnVlIG9ubHkgZm9yIGVzY3Jvd3MgdGhpcwpmYWN0b3J5IGRlcGxveWVkLgAAAAAABmlzX2pvYgAAAAAAAQAAAAAAAAAHYWRkcmVzcwAAAAATAAAAAQAAAAE=",
        "AAAAAAAAAAAAAAAJZ2V0X2FkbWluAAAAAAAAAAAAAAEAAAAT",
        "AAAAAAAAAAAAAAAJam9iX2NvdW50AAAAAAAAAAAAAAEAAAAE",
        "AAAAAAAAAAAAAAAJbGlzdF9qb2JzAAAAAAAAAAAAAAEAAAPqAAAAEw==",
        "AAAAAAAAAKNEZXBsb3lzIGEgZnJlc2ggZXNjcm93IGZvciBvbmUgZW5nYWdlbWVudCBhbmQgcmVjb3JkcyBpdCwgc28gdGhhdCB0aGUgcmVwdXRhdGlvbgpjb250cmFjdCBjYW4gbGF0ZXIgY29uZmlybSDigJQgdmlhIGBpc19qb2JgIOKAlCB0aGF0IHRoZSBlc2Nyb3cgaXMgZ2VudWluZWx5IG91cnMuAAAAAApjcmVhdGVfam9iAAAAAAAGAAAAAAAAAAZjbGllbnQAAAAAABMAAAAAAAAACmZyZWVsYW5jZXIAAAAAABMAAAAAAAAAB2FyYml0ZXIAAAAAEwAAAAAAAAAFdG9rZW4AAAAAAAATAAAAAAAAAAdhbW91bnRzAAAAA+oAAAALAAAAAAAAAAhkZWFkbGluZQAAAAYAAAABAAAD6QAAABMAAAAD",
        "AAAAAAAAAAAAAAANX19jb25zdHJ1Y3RvcgAAAAAAAAIAAAAAAAAABWFkbWluAAAAAAAAEwAAAAAAAAAIam9iX3dhc20AAAPuAAAAIAAAAAA=",
        "AAAAAAAAAAAAAAAOZ2V0X3JlcHV0YXRpb24AAAAAAAAAAAABAAAD6QAAABMAAAAD",
        "AAAAAAAAAMdXaXJlcyBpbiB0aGUgcmVwdXRhdGlvbiBjb250cmFjdC4gU2VwYXJhdGUgZnJvbSB0aGUgY29uc3RydWN0b3IgYmVjYXVzZSB0aGUKcmVwdXRhdGlvbiBjb250cmFjdCBuZWVkcyB0aGlzIGZhY3RvcnkncyBhZGRyZXNzIHRvIGV4aXN0IGZpcnN0LCBzbyB0aGUgdHdvIGFyZQpkZXBsb3llZCBpbiBzZXF1ZW5jZSBhbmQgbGlua2VkIGFmdGVyd2FyZHMuAAAAAA5zZXRfcmVwdXRhdGlvbgAAAAAAAQAAAAAAAAAKcmVwdXRhdGlvbgAAAAAAEwAAAAA=" ]),
      options
    )
  }
  public readonly fromJSON = {
    is_job: this.txFromJSON<boolean>,
        get_admin: this.txFromJSON<string>,
        job_count: this.txFromJSON<u32>,
        list_jobs: this.txFromJSON<Array<string>>,
        create_job: this.txFromJSON<Result<string>>,
        get_reputation: this.txFromJSON<Result<string>>,
        set_reputation: this.txFromJSON<null>
  }
}