// @ts-nocheck — generated by `stellar contract bindings typescript`; not hand-maintained.
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import { Client as ContractClient, Spec as ContractSpec } from "@stellar/stellar-sdk/contract";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CDUR5FLDZGYHHYZJ4E5ATVLNIB7VHCVEAWZUOGOP7UVKPKWYCACATVEK",
  }
} as const

export const Errors = {
  1: {message:"NotInitialized"},
  2: {message:"NoMilestones"},
  3: {message:"InvalidAmount"},
  4: {message:"InvalidDeadline"},
  5: {message:"UnknownMilestone"},
  6: {message:"WrongState"},
  7: {message:"InvalidRating"},
  8: {message:"NotAParty"},
  9: {message:"DeadlineNotPassed"},
  10: {message:"NothingToRefund"}
}


export type DataKey = {tag: "Job", values: void} | {tag: "Milestones", values: void};


export interface JobData {
  arbiter: string;
  client: string;
  deadline: u64;
  freelancer: string;
  reputation: string;
  token: string;
}






export interface Milestone {
  amount: i128;
  rating: u32;
  state: MilestoneState;
}


/**
 * The lifecycle of a single milestone's escrowed funds.
 */
export type MilestoneState = {tag: "Funded", values: void} | {tag: "Submitted", values: void} | {tag: "Disputed", values: void} | {tag: "Approved", values: void} | {tag: "Refunded", values: void};

export interface Client {
  /**
   * Construct and simulate a submit transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Freelancer marks a milestone's work as delivered, ready for the client to review.
   */
  submit: ({milestone}: {milestone: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a approve transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Client accepts the delivered work: the freelancer is paid and rated, and the
   * rating is recorded to their on-chain reputation.
   */
  approve: ({milestone, rating}: {milestone: u32, rating: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a dispute transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Either party can escalate a milestone to the arbiter — the client if a submission
   * is unsatisfactory, the freelancer if the client will not approve delivered work.
   */
  dispute: ({caller, milestone}: {caller: string, milestone: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a get_job transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_job: (options?: MethodOptions) => Promise<AssembledTransaction<Result<JobData>>>

  /**
   * Construct and simulate a resolve transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Arbiter decides a disputed milestone. In the freelancer's favour they are paid;
   * against them the client is refunded and the loss is recorded to their reputation.
   */
  resolve: ({milestone, pay_freelancer}: {milestone: u32, pay_freelancer: boolean}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a get_milestones transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_milestones: (options?: MethodOptions) => Promise<AssembledTransaction<Array<Milestone>>>

  /**
   * Construct and simulate a refund_expired transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * After the deadline, the client reclaims any milestone the freelancer never
   * delivered. Approved and disputed milestones are untouched.
   */
  refund_expired: ({milestone}: {milestone: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
        /** Constructor/Initialization Args for the contract's `__constructor` method */
        {client, freelancer, arbiter, token, reputation, amounts, deadline}: {client: string, freelancer: string, arbiter: string, token: string, reputation: string, amounts: Array<i128>, deadline: u64},
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy({client, freelancer, arbiter, token, reputation, amounts, deadline}, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAAAAAAAFFGcmVlbGFuY2VyIG1hcmtzIGEgbWlsZXN0b25lJ3Mgd29yayBhcyBkZWxpdmVyZWQsIHJlYWR5IGZvciB0aGUgY2xpZW50IHRvIHJldmlldy4AAAAAAAAGc3VibWl0AAAAAAABAAAAAAAAAAltaWxlc3RvbmUAAAAAAAAEAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAAH1DbGllbnQgYWNjZXB0cyB0aGUgZGVsaXZlcmVkIHdvcms6IHRoZSBmcmVlbGFuY2VyIGlzIHBhaWQgYW5kIHJhdGVkLCBhbmQgdGhlCnJhdGluZyBpcyByZWNvcmRlZCB0byB0aGVpciBvbi1jaGFpbiByZXB1dGF0aW9uLgAAAAAAAAdhcHByb3ZlAAAAAAIAAAAAAAAACW1pbGVzdG9uZQAAAAAAAAQAAAAAAAAABnJhdGluZwAAAAAABAAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAKRFaXRoZXIgcGFydHkgY2FuIGVzY2FsYXRlIGEgbWlsZXN0b25lIHRvIHRoZSBhcmJpdGVyIOKAlCB0aGUgY2xpZW50IGlmIGEgc3VibWlzc2lvbgppcyB1bnNhdGlzZmFjdG9yeSwgdGhlIGZyZWVsYW5jZXIgaWYgdGhlIGNsaWVudCB3aWxsIG5vdCBhcHByb3ZlIGRlbGl2ZXJlZCB3b3JrLgAAAAdkaXNwdXRlAAAAAAIAAAAAAAAABmNhbGxlcgAAAAAAEwAAAAAAAAAJbWlsZXN0b25lAAAAAAAABAAAAAEAAAPpAAAAAgAAAAM=",
        "AAAAAAAAAAAAAAAHZ2V0X2pvYgAAAAAAAAAAAQAAA+kAAAfQAAAAB0pvYkRhdGEAAAAAAw==",
        "AAAAAAAAAKFBcmJpdGVyIGRlY2lkZXMgYSBkaXNwdXRlZCBtaWxlc3RvbmUuIEluIHRoZSBmcmVlbGFuY2VyJ3MgZmF2b3VyIHRoZXkgYXJlIHBhaWQ7CmFnYWluc3QgdGhlbSB0aGUgY2xpZW50IGlzIHJlZnVuZGVkIGFuZCB0aGUgbG9zcyBpcyByZWNvcmRlZCB0byB0aGVpciByZXB1dGF0aW9uLgAAAAAAAAdyZXNvbHZlAAAAAAIAAAAAAAAACW1pbGVzdG9uZQAAAAAAAAQAAAAAAAAADnBheV9mcmVlbGFuY2VyAAAAAAABAAAAAQAAA+kAAAACAAAAAw==",
        "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAACgAAAAAAAAAOTm90SW5pdGlhbGl6ZWQAAAAAAAEAAAAAAAAADE5vTWlsZXN0b25lcwAAAAIAAAAAAAAADUludmFsaWRBbW91bnQAAAAAAAADAAAAAAAAAA9JbnZhbGlkRGVhZGxpbmUAAAAABAAAAAAAAAAQVW5rbm93bk1pbGVzdG9uZQAAAAUAAAAAAAAACldyb25nU3RhdGUAAAAAAAYAAAAAAAAADUludmFsaWRSYXRpbmcAAAAAAAAHAAAAAAAAAAlOb3RBUGFydHkAAAAAAAAIAAAAAAAAABFEZWFkbGluZU5vdFBhc3NlZAAAAAAAAAkAAAAAAAAAD05vdGhpbmdUb1JlZnVuZAAAAAAK",
        "AAAABQAAAAAAAAAAAAAABkZ1bmRlZAAAAAAAAQAAAAZmdW5kZWQAAAAAAAMAAAAAAAAABmNsaWVudAAAAAAAEwAAAAEAAAAAAAAABXRvdGFsAAAAAAAACwAAAAAAAAAAAAAACm1pbGVzdG9uZXMAAAAAAAQAAAAAAAAAAg==",
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAAAgAAAAAAAAAAAAAAA0pvYgAAAAAAAAAAAAAAAApNaWxlc3RvbmVzAAA=",
        "AAAAAQAAAAAAAAAAAAAAB0pvYkRhdGEAAAAABgAAAAAAAAAHYXJiaXRlcgAAAAATAAAAAAAAAAZjbGllbnQAAAAAABMAAAAAAAAACGRlYWRsaW5lAAAABgAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAAAAAAKcmVwdXRhdGlvbgAAAAAAEwAAAAAAAAAFdG9rZW4AAAAAAAAT",
        "AAAABQAAAAAAAAAAAAAACEFwcHJvdmVkAAAAAQAAAAhhcHByb3ZlZAAAAAQAAAAAAAAACmZyZWVsYW5jZXIAAAAAABMAAAABAAAAAAAAAAltaWxlc3RvbmUAAAAAAAAEAAAAAAAAAAAAAAAGYW1vdW50AAAAAAALAAAAAAAAAAAAAAAGcmF0aW5nAAAAAAAEAAAAAAAAAAI=",
        "AAAABQAAAAAAAAAAAAAACERpc3B1dGVkAAAAAQAAAAhkaXNwdXRlZAAAAAIAAAAAAAAACXJhaXNlZF9ieQAAAAAAABMAAAABAAAAAAAAAAltaWxlc3RvbmUAAAAAAAAEAAAAAAAAAAI=",
        "AAAABQAAAAAAAAAAAAAACFJlZnVuZGVkAAAAAQAAAAhyZWZ1bmRlZAAAAAMAAAAAAAAABmNsaWVudAAAAAAAEwAAAAEAAAAAAAAACW1pbGVzdG9uZQAAAAAAAAQAAAAAAAAAAAAAAAZhbW91bnQAAAAAAAsAAAAAAAAAAg==",
        "AAAABQAAAAAAAAAAAAAACFJlc29sdmVkAAAAAQAAAAhyZXNvbHZlZAAAAAMAAAAAAAAACW1pbGVzdG9uZQAAAAAAAAQAAAABAAAAAAAAAA9wYWlkX2ZyZWVsYW5jZXIAAAAAAQAAAAAAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAC",
        "AAAAAQAAAAAAAAAAAAAACU1pbGVzdG9uZQAAAAAAAAMAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAGcmF0aW5nAAAAAAAEAAAAAAAAAAVzdGF0ZQAAAAAAB9AAAAAOTWlsZXN0b25lU3RhdGUAAA==",
        "AAAAAAAAAJBTZXRzIHVwIHRoZSBlc2Nyb3cgYW5kIHB1bGxzIHRoZSBmdWxsIGJ1ZGdldCBmcm9tIHRoZSBjbGllbnQgdXAgZnJvbnQsIHNvIGEKZnJlZWxhbmNlciBjYW4gdHJ1c3QgdGhlIG1vbmV5IGV4aXN0cyBiZWZvcmUgc3RhcnRpbmcgYW55IG1pbGVzdG9uZS4AAAANX19jb25zdHJ1Y3RvcgAAAAAAAAcAAAAAAAAABmNsaWVudAAAAAAAEwAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAAAAAAHYXJiaXRlcgAAAAATAAAAAAAAAAV0b2tlbgAAAAAAABMAAAAAAAAACnJlcHV0YXRpb24AAAAAABMAAAAAAAAAB2Ftb3VudHMAAAAD6gAAAAsAAAAAAAAACGRlYWRsaW5lAAAABgAAAAEAAAPpAAAAAgAAAAM=",
        "AAAABQAAAAAAAAAAAAAACVN1Ym1pdHRlZAAAAAAAAAEAAAAJc3VibWl0dGVkAAAAAAAAAgAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAEAAAAAAAAACW1pbGVzdG9uZQAAAAAAAAQAAAAAAAAAAg==",
        "AAAAAAAAAAAAAAAOZ2V0X21pbGVzdG9uZXMAAAAAAAAAAAABAAAD6gAAB9AAAAAJTWlsZXN0b25lAAAA",
        "AAAAAAAAAIVBZnRlciB0aGUgZGVhZGxpbmUsIHRoZSBjbGllbnQgcmVjbGFpbXMgYW55IG1pbGVzdG9uZSB0aGUgZnJlZWxhbmNlciBuZXZlcgpkZWxpdmVyZWQuIEFwcHJvdmVkIGFuZCBkaXNwdXRlZCBtaWxlc3RvbmVzIGFyZSB1bnRvdWNoZWQuAAAAAAAADnJlZnVuZF9leHBpcmVkAAAAAAABAAAAAAAAAAltaWxlc3RvbmUAAAAAAAAEAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAgAAADVUaGUgbGlmZWN5Y2xlIG9mIGEgc2luZ2xlIG1pbGVzdG9uZSdzIGVzY3Jvd2VkIGZ1bmRzLgAAAAAAAAAAAAAOTWlsZXN0b25lU3RhdGUAAAAAAAUAAAAAAAAAAAAAAAZGdW5kZWQAAAAAAAAAAAAAAAAACVN1Ym1pdHRlZAAAAAAAAAAAAAAAAAAACERpc3B1dGVkAAAAAAAAAAAAAAAIQXBwcm92ZWQAAAAAAAAAAAAAAAhSZWZ1bmRlZA==" ]),
      options
    )
  }
  public readonly fromJSON = {
    submit: this.txFromJSON<Result<void>>,
        approve: this.txFromJSON<Result<void>>,
        dispute: this.txFromJSON<Result<void>>,
        get_job: this.txFromJSON<Result<JobData>>,
        resolve: this.txFromJSON<Result<void>>,
        get_milestones: this.txFromJSON<Array<Milestone>>,
        refund_expired: this.txFromJSON<Result<void>>
  }
}