// @ts-nocheck — generated by `stellar contract bindings typescript`; not hand-maintained.
import { Buffer } from "buffer";
import { Address } from "@stellar/stellar-sdk";
import { Client as ContractClient, Spec as ContractSpec } from "@stellar/stellar-sdk/contract";
import type {
  AssembledTransaction,
  ClientOptions as ContractClientOptions,
  MethodOptions,
  Result,
} from "@stellar/stellar-sdk/contract";
import type {
  u32,
  i32,
  u64,
  i64,
  u128,
  i128,
  u256,
  i256,
  Option,
  Timepoint,
  Duration,
} from "@stellar/stellar-sdk/contract";
export * from "@stellar/stellar-sdk";
export * as contract from "@stellar/stellar-sdk/contract";
export * as rpc from "@stellar/stellar-sdk/rpc";

if (typeof window !== "undefined") {
  //@ts-ignore Buffer exists
  window.Buffer = window.Buffer || Buffer;
}


export const networks = {
  testnet: {
    networkPassphrase: "Test SDF Network ; September 2015",
    contractId: "CBYTQSZNGI6CKC7XLYAIQRODWI47OVRKKOOLG7GZXOBWIHM7TPMBY2MG",
  }
} as const

export const Errors = {
  1: {message:"AlreadyInitialized"},
  2: {message:"NotInitialized"},
  3: {message:"UnknownJob"},
  4: {message:"InvalidRating"},
  5: {message:"InvalidAmount"}
}


/**
 * A freelancer's standing. Ratings are stored as a sum and a count rather than an
 * average so the contract never has to store a fraction.
 */
export interface Score {
  disputes_lost: u32;
  jobs_completed: u32;
  milestones_completed: u32;
  rating_count: u32;
  rating_sum: u32;
  total_earned: i128;
}

export type DataKey = {tag: "Factory", values: void} | {tag: "Score", values: readonly [string]};




export interface Client {
  /**
   * Construct and simulate a get_score transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_score: ({freelancer}: {freelancer: string}, options?: MethodOptions) => Promise<AssembledTransaction<Score>>

  /**
   * Construct and simulate a get_factory transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   */
  get_factory: (options?: MethodOptions) => Promise<AssembledTransaction<Result<string>>>

  /**
   * Construct and simulate a record_milestone transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Credits a freelancer for an approved milestone. Callable only by a job contract
   * the factory deployed — see `require_registered_job`.
   */
  record_milestone: ({job, freelancer, amount, rating}: {job: string, freelancer: string, amount: i128, rating: u32}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a record_dispute_lost transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Records that an arbiter resolved a dispute against the freelancer.
   */
  record_dispute_lost: ({job, freelancer}: {job: string, freelancer: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

  /**
   * Construct and simulate a record_job_completed transaction. Returns an `AssembledTransaction` object which will have a `result` field containing the result of the simulation. If this transaction changes contract state, you will need to call `signAndSend()` on the returned object.
   * Marks a whole engagement finished, once its final milestone is approved.
   */
  record_job_completed: ({job, freelancer}: {job: string, freelancer: string}, options?: MethodOptions) => Promise<AssembledTransaction<Result<void>>>

}
export class Client extends ContractClient {
  static async deploy<T = Client>(
        /** Constructor/Initialization Args for the contract's `__constructor` method */
        {factory}: {factory: string},
    /** Options for initializing a Client as well as for calling a method, with extras specific to deploying. */
    options: MethodOptions &
      Omit<ContractClientOptions, "contractId"> & {
        /** The hash of the Wasm blob, which must already be installed on-chain. */
        wasmHash: Buffer | string;
        /** Salt used to generate the contract's ID. Passed through to {@link Operation.createCustomContract}. Default: random. */
        salt?: Buffer | Uint8Array;
        /** The format used to decode `wasmHash`, if it's provided as a string. */
        format?: "hex" | "base64";
      }
  ): Promise<AssembledTransaction<T>> {
    return ContractClient.deploy({factory}, options)
  }
  constructor(public readonly options: ContractClientOptions) {
    super(
      new ContractSpec([ "AAAABAAAAAAAAAAAAAAABUVycm9yAAAAAAAABQAAAAAAAAASQWxyZWFkeUluaXRpYWxpemVkAAAAAAABAAAAAAAAAA5Ob3RJbml0aWFsaXplZAAAAAAAAgAAAAAAAAAKVW5rbm93bkpvYgAAAAAAAwAAAAAAAAANSW52YWxpZFJhdGluZwAAAAAAAAQAAAAAAAAADUludmFsaWRBbW91bnQAAAAAAAAF",
        "AAAAAQAAAIZBIGZyZWVsYW5jZXIncyBzdGFuZGluZy4gUmF0aW5ncyBhcmUgc3RvcmVkIGFzIGEgc3VtIGFuZCBhIGNvdW50IHJhdGhlciB0aGFuIGFuCmF2ZXJhZ2Ugc28gdGhlIGNvbnRyYWN0IG5ldmVyIGhhcyB0byBzdG9yZSBhIGZyYWN0aW9uLgAAAAAAAAAAAAVTY29yZQAAAAAAAAYAAAAAAAAADWRpc3B1dGVzX2xvc3QAAAAAAAAEAAAAAAAAAA5qb2JzX2NvbXBsZXRlZAAAAAAABAAAAAAAAAAUbWlsZXN0b25lc19jb21wbGV0ZWQAAAAEAAAAAAAAAAxyYXRpbmdfY291bnQAAAAEAAAAAAAAAApyYXRpbmdfc3VtAAAAAAAEAAAAAAAAAAx0b3RhbF9lYXJuZWQAAAAL",
        "AAAAAgAAAAAAAAAAAAAAB0RhdGFLZXkAAAAAAgAAAAAAAAAAAAAAB0ZhY3RvcnkAAAAAAQAAAAAAAAAFU2NvcmUAAAAAAAABAAAAEw==",
        "AAAABQAAAAAAAAAAAAAAC0Rpc3B1dGVMb3N0AAAAAAEAAAAMZGlzcHV0ZV9sb3N0AAAAAgAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAEAAAAAAAAAA2pvYgAAAAATAAAAAAAAAAI=",
        "AAAAAAAAAAAAAAAJZ2V0X3Njb3JlAAAAAAAAAQAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAEAAAfQAAAABVNjb3JlAAAA",
        "AAAABQAAAAAAAAAAAAAADEpvYkNvbXBsZXRlZAAAAAEAAAANam9iX2NvbXBsZXRlZAAAAAAAAAMAAAAAAAAACmZyZWVsYW5jZXIAAAAAABMAAAABAAAAAAAAAANqb2IAAAAAEwAAAAAAAAAAAAAADmpvYnNfY29tcGxldGVkAAAAAAAEAAAAAAAAAAI=",
        "AAAAAAAAAAAAAAALZ2V0X2ZhY3RvcnkAAAAAAAAAAAEAAAPpAAAAEwAAAAM=",
        "AAAAAAAAAAAAAAANX19jb25zdHJ1Y3RvcgAAAAAAAAEAAAAAAAAAB2ZhY3RvcnkAAAAAEwAAAAA=",
        "AAAABQAAAAAAAAAAAAAAEU1pbGVzdG9uZVJlY29yZGVkAAAAAAAAAQAAABJtaWxlc3RvbmVfcmVjb3JkZWQAAAAAAAQAAAAAAAAACmZyZWVsYW5jZXIAAAAAABMAAAABAAAAAAAAAANqb2IAAAAAEwAAAAAAAAAAAAAABmFtb3VudAAAAAAACwAAAAAAAAAAAAAABnJhdGluZwAAAAAABAAAAAAAAAAC",
        "AAAAAAAAAIZDcmVkaXRzIGEgZnJlZWxhbmNlciBmb3IgYW4gYXBwcm92ZWQgbWlsZXN0b25lLiBDYWxsYWJsZSBvbmx5IGJ5IGEgam9iIGNvbnRyYWN0CnRoZSBmYWN0b3J5IGRlcGxveWVkIOKAlCBzZWUgYHJlcXVpcmVfcmVnaXN0ZXJlZF9qb2JgLgAAAAAAEHJlY29yZF9taWxlc3RvbmUAAAAEAAAAAAAAAANqb2IAAAAAEwAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAAAAAAGYW1vdW50AAAAAAALAAAAAAAAAAZyYXRpbmcAAAAAAAQAAAABAAAD6QAAAAIAAAAD",
        "AAAAAAAAAEJSZWNvcmRzIHRoYXQgYW4gYXJiaXRlciByZXNvbHZlZCBhIGRpc3B1dGUgYWdhaW5zdCB0aGUgZnJlZWxhbmNlci4AAAAAABNyZWNvcmRfZGlzcHV0ZV9sb3N0AAAAAAIAAAAAAAAAA2pvYgAAAAATAAAAAAAAAApmcmVlbGFuY2VyAAAAAAATAAAAAQAAA+kAAAACAAAAAw==",
        "AAAAAAAAAEhNYXJrcyBhIHdob2xlIGVuZ2FnZW1lbnQgZmluaXNoZWQsIG9uY2UgaXRzIGZpbmFsIG1pbGVzdG9uZSBpcyBhcHByb3ZlZC4AAAAUcmVjb3JkX2pvYl9jb21wbGV0ZWQAAAACAAAAAAAAAANqb2IAAAAAEwAAAAAAAAAKZnJlZWxhbmNlcgAAAAAAEwAAAAEAAAPpAAAAAgAAAAM=" ]),
      options
    )
  }
  public readonly fromJSON = {
    get_score: this.txFromJSON<Score>,
        get_factory: this.txFromJSON<Result<string>>,
        record_milestone: this.txFromJSON<Result<void>>,
        record_dispute_lost: this.txFromJSON<Result<void>>,
        record_job_completed: this.txFromJSON<Result<void>>
  }
}